development:
  adapter:  sqlite3
  host:     localhost
  encoding: unicode
  database: railsroots_development
  pool:     5
  username: yourusername
  password:

test:
  adapter:  sqlite3
  host:     localhost
  encoding: unicode
  database: railsroots_test
  pool:     5
  username: yourusername
  password:

production:
  adapter:  sqlite3
  host:     localhost
  encoding: unicode
  database: railsroots_production
  pool:     5
  username: yourusername
  password:
